apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portscanning
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
    resourceNames: ["portscanning"]

