apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portscanning
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: portscanning
subjects:
  - kind: ServiceAccount
    name: portscanning
    namespace: {{ .Values.namespace }}
